trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: |
    echo "Installing Terraform..."
    wget https://releases.hashicorp.com/terraform/1.5.7/terraform_1.5.7_linux_amd64.zip
    unzip terraform_1.5.7_linux_amd64.zip
    sudo mv terraform /usr/local/bin/
    terraform --version
  displayName: 'Install Terraform'

- task: AzureCLI@2
  displayName: 'Azure Login + Terraform'
  inputs:
    azureSubscription: 'azure-service-conn'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      echo "Logged in Azure account:"
      az account show

      echo "Running Terraform..."
      terraform init
      terraform plan