trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: AzureCLI@2
  displayName: 'Azure Login + Terraform'
  inputs:
    azureSubscription: 'azure-service-conn'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      echo "Logged in Azure account:"
      az account show

      echo "Running Terraform..."
      terraform init
      terraform plan